package com.priyansu.haki.models;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotEmpty;
import lombok.*;

/**
 * @author Priyansu Sahoo
 * 11-04-2024
 * @Project haki
 */

@Data // Getter(), Setter(), toString(), equals(), hashCode()
@Entity // Map the class to DB
@Builder // Software Design Pattern : Builder design Pattern
@NoArgsConstructor // create no args constructor
@AllArgsConstructor // create all args constructor
@Table(name = "product") // specifies the name of the database table associated with this entity
@EqualsAndHashCode(callSuper = false) // generate equals() and hashCode() only on the fields in this class and not in any superclass.
public class Product {
    @Id // primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // strategy for generating the primary key values, "IDENTITY" strategy indicates that the primary key values will be automatically generated by the database
    private long Id;

    @NotEmpty(message = "Name cannot be blank") // checks if a value is not null and not empty
    @Column(unique = true)
    private String name;

    private long quantity;
    private double unitPrice;
}